language: julia

os:
    - linux
    - osx

julia:
    - 1.0
    - 1.1
    - 1.2
    - nightly

codecov: true

jobs:
    include:
        - state: "Documentation"
          julia: 1.1
          os: linux
          script:
              - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                          Pkg.instantiate()'
              - julia --project=docs/ docs/make.jl
          after_success: skip
